TDOAuth.swift refinement
yahoo/TDOAuth pull request #44
Opened 2022-10-27 08:44 UTC by WinnieLYT

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

This PR is to fix:
- Some parameters are dropped because insufficient type casting on `TDOQueryItem`.
- Encoding JSON object's `httpBody` failure
- Add tests for `TDOQueryItem` to make sure the type casting is correct.

2022-10-27 23:57 UTC, adamkaplan requested changes
Thanks for the contribution and extra thanks for the tests! I left one comment in the Switch that should be addressed.

2022-10-27 23:57 UTC, adamkaplan commented on Source/compat/TDOAuth.swift
> +        case let losslessString as LosslessStringConvertible:
String conforms LosslessStringConvertible per the docs, as do several of the rest. This one should be after String and other direct conversions or they’ll never be called. it’s not clear to me if the new lossless convertible for something like bool is better/worse than the dedicated initializer. Maybe we can remove most of the cases here.

2022-10-27 23:57 UTC, adamkaplan commented on Source/compat/TDOAuth.swift
> +            formattedValue = String(describing: arrayValue)
Nice! My only concern with this is that there is no intent captured. Without an output contract here it seems possible that future implementations could break. I think it would interesting to add an extension of “Array where Element conforms to LosslessStringConvertible”, which conforms the array to the same method by concatenating in the exact format needed.


But, this is good for now.

2022-10-28 11:15 UTC, WinnieLYT commented on Source/compat/TDOAuth.swift
> +            formattedValue = String(describing: arrayValue)
Thanks, @adamkaplan. Previously I kept those cases of `NSNumber`, `String` and `Bool` because `LosslessStringConvertible` doesn't take care of some Obj-C object types. Finally, my team provides me a better way of using `NSObjectProtocol`.
Please see if this is good to you.

2022-10-30 13:45 UTC, adamkaplan approved these changes
Thanks!

2022-10-31 15:31 UTC, WinnieLYT commented
@stury done.

2022-10-31 15:46 UTC, stury approved these changes

2022-10-31 15:56 UTC, merged